scene_path=sim.getStringParameter(sim.stringparam_scene_path)
im=simIM.read(scene_path..'/lena.bmp')
simIM.rgb2hsv(im,true)
hsv=simIM.split(im)
simIM.write(hsv[1],scene_path..'/test-hsv-h.jpg')
simIM.write(hsv[2],scene_path..'/test-hsv-s.jpg')
simIM.write(hsv[3],scene_path..'/test-hsv-v.jpg')
simIM.destroy(hsv[1])
simIM.destroy(hsv[2])
simIM.destroy(hsv[3])
simIM.destroy(im)
print(simIM.numActiveHandles()..' active handles')
